# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 4
format = " [$path](fg:white) "

[cmd_duration]
format = "[$duration]($style) "
style = "italic #666666"

[git_status]
format = "([$ahead_behind$modified$staged]($style) )"
ahead = "[\u2191](fg:green)"
behind = "[\u2193](fg:green)"
conflicted = "!"
staged = "[+](fg:green)"
modified = "[~](fg:yellow)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "\uf418 "
